<?php
/**
 * Created by PhpStorm.
 * User: jomon
 * Date: 22/11/18
 * Time: 11:59 AM
 */

/**
 * @property BaseMailQueue $mailqueue
 */
abstract class BaseApplication extends yii\base\Application
{

}

/**
 * Class BaseMailQueue
 */
abstract class BaseMailQueue extends \codexten\yii\mailqueue\MailQueue
{
    /**
     * @param null $view
     * @param array $params
     *
     * @return \codexten\yii\mailqueue\Message
     */
    public function compose($view = null, array $params = [])
    {
        return parent::compose($view, $params); // TODO: Change the autogenerated stub
    }

}